# Generated by Django 5.1.7 on 2025-03-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swida_assignment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportorder',
            name='order_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
